package cn.homj.autogen4j.support.openai.chat.tool;

import lombok.Data;
import lombok.experimental.Accessors;

/**
 * @author jiehong.jh
 * @date 2023/11/27
 */
@Data
@Accessors(chain = true)
public class FunctionCall {
    /**
     * The name of the function to call.
     */
    private String name;
    /**
     * The arguments to call the function with, as generated by the model in JSON format.
     */
    private String arguments;
}
